(use-package lsp-mode)
(use-package lsp-ui :commands lsp-ui-mode)
(use-package helm-lsp :commands helm-lsp-workspace-symbol)
(use-package lsp-treemacs :commands lsp-treemacs-errors-list)
(setq lsp-completion-provider :capf)
(setq lsp-idle-delay 0.500)
(setq lsp-auto-guess-root nil)
(setq lsp-ui-sideline-show-diagnostics t)
(setq lsp-ui-sideline-show-hover t)
(setq lsp-ui-doc-enable t)
(setq lsp-ui-doc-position 'at-point)
(global-leader
  "l" '(:ignore t :which-key "lsp")
  "l=" '(:ignore t :which-key "format")
  "lf" '(:ignore t :which-key "workspace")
  "lg" '(:ignore t :which-key "goto")
  "lt" '(:ignore t :which-key "tree")
  "la" '(:ignore t :which-key "action")
  "lh" '(:ignore t :which-key "help")
  "lr" '(:ignore t :which-key "rename")
  "ls" '(:ignore t :which-key "server")
  "lm" '(lsp-ui-imenu :which-key "imenu")
  "laa" '(lsp-execute-code-action :which-key "execute code action")
  "lah" '(lsp-document-highlight :which-key "highlight")
  "lro" '(lsp-organize-imports :which-key "organize imports")
  "lrr" '(lsp-rename :which-key "rename")
  "lhg" '(lsp-ui-doc-glance :which-key "doc glance")
  "lhh" '(lsp-describe-thing-at-point :which-key "describe thing at point")
  "lhs" '(lsp-signature-activate :which-key "signature activate")
  "lge" '(lsp-treemacs-errors-list :which-key "treemacs errors list")
  "lgg" '(lsp-find-definition :which-key "defination")
  "lgh" '(lsp-treemacs-call-hierarchy :which-key "treemacs call hierarchy")
  "lgr" '(lsp-find-references :which-key "references")
  "ltd" '(lsp-modeline-diagnostics-mode :which-key "modeline diagnostics mode")
  "ltl" '(lsp-toggle-trace-io :which-key "toggle trace io")
  "lts" '(lsp-ui-sideline-mode :which-key "ui sideline mode")
  "ltt" '(lsp-treemacs-sync-mode :which-key "treemacs sync mode")
  "lta" '(lsp-modeline-code-actions-mode :which-key "modeline code actions mode")
  "ltb" '(lsp-headerline-breadcrumb-mode :which-key "headerline breadcrumb mode")
  "ltd" '(lsp-ui-doc-mode :which-key "ui doc mode")
  "lth" '(lsp-toggle-symbol-highlight :which-key "toggle symbol highlight")
  "ltl" '(lsp-lens-mode :which-key "lens mode")
  "lts" '(lsp-toggle-signature-auto-activate :which-key "toggle signature auto activate")
  "lfa" '(lsp-workspace-folders-add :which-key "folders add")
  "lfb" '(lsp-workspace-blacklist-remove :which-key "blacklist remove")
  "lfr" '(lsp-workspace-folders-remove :which-key "folders remove")
  "l==" '(lsp-format-buffer :which-key "buffer")
  "l=r" '(lsp-format-region :which-key "region")
  "lsd" '(lsp-disconnect :which-key "disconnect")
  "lsd" '(lsp-describe-session :which-key "describe session")
  "lsq" '(lsp-workspace-shutdown :which-key "workspace shutdown")
  "lsr" '(lsp-workspace-restart :which-key "workspace restart")
  "lss" '(lsp :which-key "start/restart")
)

(provide 'lsp-setup)

